import"./assets/modulepreload-polyfill-3cfb730f.js";/* empty css                      */import{a as l,S as L,i as w}from"./assets/vendor-b851b841.js";const c=40,e={page:1,per_page:c,receivedHits:0,searchQuery:null,isLoading:!1,isScrollListenerAdded:!1},t={form:document.querySelector(".search-form"),gallery:document.querySelector(".gallery"),loader:document.querySelector(".loader"),submitButton:document.querySelector('[type="submit"]')},d={API_KEY:"44202133-14fac6110a8eccaaec992feaf",AXIOS_KEY:"live_nOdnL3Dj9jjF4zVLjteozldoqmiVUxxCRsrlPoRVyonLQDm4DFuaUNiaRzafsnXC"},b="https://pixabay.com/api/";l.defaults.headers.common["x-api-key"]=d.AXIOS_KEY;l.defaults.headers=["Access-Control-Allow-Origin"];async function v(){const a=new URLSearchParams({key:d.API_KEY,q:e.searchQuery,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:e.per_page,page:e.page});return await(await l.get(`${b}?${a}`)).data}const m=new L(".gallery a",{captionsData:"alt",captionDelay:250});m.on("error.simplelightbox",function(a){console.log(a)});t.form.addEventListener("submit",S);function n(){window.scrollY+window.innerHeight>=document.documentElement.scrollHeight-50&&u()}async function S(a){a.preventDefault(),e.isScrollListenerAdded||(window.addEventListener("scroll",n),e.isScrollListenerAdded=!0);const r=new FormData(a.currentTarget);if(e.searchQuery=r.get("searchQuery").trim(),t.form.reset(),!e.searchQuery){o("Please enter a search query.","error"),t.loader.classList.add("hide"),e.isLoading=!1;return}e.page=1,e.receivedHits=0,e.per_page=c,t.gallery.innerHTML="",t.loader.classList.remove("hide"),await u(!0)}async function u(a=!1){if(!e.isLoading){e.isLoading=!0,t.loader.classList.remove("hide"),t.submitButton.disabled=!0;try{const{totalHits:r,hits:s}=await v();if(!r||!(s!=null&&s.length)){o("Sorry, there are no images matching your search query. Please try again.","error");return}if(A(s),m.refresh(),e.page++,e.per_page=Math.min(r-e.receivedHits,c),e.receivedHits+=s.length,a)o(`Hooray! We found ${r} images.`,"success");else{const{height:i}=t.gallery.firstElementChild.getBoundingClientRect();window.scrollBy({top:i*2,behavior:"smooth"})}a&&e.per_page>=r&&(window.removeEventListener("scroll",n),e.isScrollListenerAdded=!1),e.receivedHits>=r&&(setTimeout(()=>{o("We're sorry, but you've reached the end of search results.","info")},1e3),window.removeEventListener("scroll",n),e.isScrollListenerAdded=!1)}catch{o("Error fetching data. Please try again.","error")}finally{t.loader.classList.add("hide"),t.submitButton.disabled=!1,e.isLoading=!1}}}function A(a){const r=a.map(({largeImageURL:s,webformatURL:i,tags:f,likes:g,views:p,comments:h,downloads:y})=>`
      <div class="photo-card">
        <a href="${s}" class="card-link">
          <img src="${i}" alt="${f}" class="card-image" loading="lazy" />
        </a>
        <div class="info">
          <p class="info-item"><b>Likes</b> ${g}</p>
          <p class="info-item"><b>Views</b> ${p}</p>
          <p class="info-item"><b>Comments</b> ${h}</p>
          <p class="info-item"><b>Downloads</b> ${y}</p>
        </div>
      </div>
    `).join("");t.gallery.insertAdjacentHTML("beforeend",r)}function o(a,r="info",s=3){w[r]({message:a,position:"topRight",timeout:s*1e3})}
//# sourceMappingURL=commonHelpers5.js.map
